# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages

apt_packages:
  - libtiff4-dev

after_success:
  - travis_wait 50 Rscript -e 'covr::codecov()'
